name: Deploy Static Site

on:
  push:
    branches:
      - main  # Deploy on main branch push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls -alh  # This will help you verify that your files are in the right place

      - name: Upload files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Upload the entire directory (root)
          name: site-artifact  # The name of the artifact

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          name: site-artifact  # Use the same artifact name here
