name: Deploy Static Site

on:
  push:
    branches:
      - main  # Deploy on main branch push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Static Site (Optional if you need to build first)
        run: |
          # Add any necessary build commands here
          echo "Building site..."

      - name: List files in the directory
        run: ls -alh  # Debug step to verify files

      - name: Upload files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # Ensure you're uploading the correct files (e.g., after build)
          artifact-name: site-artifact  # Optional custom name

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact-name: site-artifact  # Match the artifact name if you specified one
